[tool.black]
line-length = 99
target-version = ['py37']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs  # Optuna specific
  | tutorial  # Optuna specific
)/
'''

[tool.isort]
profile = 'black'
src_paths = ['core']
line_length = 99
lines_after_imports = 2
force_single_line = 'True'
force_sort_within_sections = 'True'
order_by_type = 'False'
